version: "3.8"

services:
  api-gateway:
    build: .
    container_name: api-gateway
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - skillsphere-net

networks:
  skillsphere-net:
    external: true
