spring.application.name=api-gateway
server.port=8083

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Spring Cloud Gateway routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**, /api/admin/**

spring.cloud.gateway.routes[1].id=skill-service
spring.cloud.gateway.routes[1].uri=lb://SKILL-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/skills/**, /api/v1/user-skills/**, /api/v1/practice-logs/**, /api/v1/admin/analytics/**, /api/v1/recommendations/**

spring.cloud.gateway.routes[2].id=reminder-service
spring.cloud.gateway.routes[2].uri=lb://REMINDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/reminder-preferences/**

# Actuator
management.endpoints.web.exposure.include=health,info

# JWT Secret
app.jwt.secret=${JWT_SECRET:your-256-bit-secret-your-256-bit-secret}
